// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/directors": {
            "post": {
                "description": "add by json director",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "directors"
                ],
                "summary": "Create new director",
                "parameters": [
                    {
                        "description": "director info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.DirectorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.DirectorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/directors/{id}": {
            "get": {
                "description": "get director by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "directors"
                ],
                "summary": "Get director by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "director info",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.DirectorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/genres": {
            "get": {
                "description": "get genres by page and limit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "genres"
                ],
                "summary": "get genres",
                "parameters": [
                    {
                        "description": "Genre",
                        "name": "genre",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.GenreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GenreResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "create genre by json",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "genres"
                ],
                "summary": "create genre",
                "parameters": [
                    {
                        "description": "Genre",
                        "name": "genre",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.GenreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GenreResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/genres/{id}": {
            "get": {
                "description": "get genre by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "genres"
                ],
                "summary": "get genre",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Genre ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GenreResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "update genre by json",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "genres"
                ],
                "summary": "update genre",
                "parameters": [
                    {
                        "description": "Update Genre",
                        "name": "genre",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.GenreRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Genre ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GenreResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete genre by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "genres"
                ],
                "summary": "delete genre",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Genre ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GenreResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/movies": {
            "post": {
                "description": "create movie by json",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movies"
                ],
                "summary": "create movie",
                "parameters": [
                    {
                        "description": "Movie",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RequestMovie"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResponseMovie"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/movies/{id}": {
            "get": {
                "description": "get movie by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movies"
                ],
                "summary": "get movie",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Movie ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ResponseMovie"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "create user by json",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "create user",
                "parameters": [
                    {
                        "description": "User",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "get user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "get user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "update user's name and/or password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "update user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update user",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "director.Director": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "2004-03-17"
                },
                "country": {
                    "type": "string",
                    "example": "Russia"
                },
                "first_name": {
                    "type": "string",
                    "example": "Alexandr"
                },
                "has_oscar": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "0ac7ee25-2ebf-4edb-91eb-3d160a0428a8"
                },
                "last_name": {
                    "type": "string",
                    "example": "Levin"
                }
            }
        },
        "genre.Genre": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "a9aec972-2c52-441a-8f17-79506cd34366"
                },
                "name": {
                    "type": "string",
                    "example": "Comedy"
                }
            }
        },
        "handlers.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@mail.com"
                },
                "password": {
                    "type": "string",
                    "example": "example_pass"
                },
                "username": {
                    "type": "string",
                    "example": "example_user"
                }
            }
        },
        "handlers.DirectorRequest": {
            "type": "object",
            "required": [
                "birth_date",
                "country",
                "first_name",
                "last_name"
            ],
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "1996-05-20"
                },
                "country": {
                    "type": "string",
                    "example": "Germany"
                },
                "first_name": {
                    "type": "string",
                    "example": "Denis"
                },
                "has_oscar": {
                    "type": "boolean",
                    "example": false
                },
                "last_name": {
                    "type": "string",
                    "example": "Levin"
                }
            }
        },
        "handlers.DirectorResponse": {
            "type": "object",
            "properties": {
                "director": {
                    "$ref": "#/definitions/director.Director"
                },
                "error": {
                    "type": "string",
                    "example": "internal error"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "handlers.GenreRequest": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 5
                },
                "name": {
                    "type": "string",
                    "example": "Comedy"
                },
                "page": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "handlers.GenreResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal error"
                },
                "genre": {
                    "$ref": "#/definitions/genre.Genre"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "handlers.RequestMovie": {
            "type": "object",
            "required": [
                "description",
                "director_id",
                "duration",
                "genres_id",
                "name",
                "rating"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "some text"
                },
                "director_id": {
                    "type": "string",
                    "example": "0ac7ee25-2ebf-4edb-91eb-3d160a0428a8"
                },
                "duration": {
                    "type": "integer",
                    "example": 3600
                },
                "genres_id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[0ac7ee25-2ebf-4edb-91eb-3d160a0428a8",
                        " 59457b31-89f8-4ade-b46c-731c61430c3e]"
                    ]
                },
                "name": {
                    "type": "string",
                    "example": "Interstellar"
                },
                "rating": {
                    "type": "number",
                    "example": 8.1
                }
            }
        },
        "handlers.ResponseMovie": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal error"
                },
                "movie": {
                    "$ref": "#/definitions/movie.Movie"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "handlers.UserResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal error"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                },
                "user": {
                    "$ref": "#/definitions/user.User"
                }
            }
        },
        "movie.Movie": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "some text"
                },
                "director_id": {
                    "type": "string",
                    "example": "0ac7ee25-2ebf-4edb-91eb-3d160a0428a8"
                },
                "duration": {
                    "type": "integer",
                    "example": 19200
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/genre.Genre"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "dc26760a-42ba-4335-92f4-e9c0f1a2a838"
                },
                "name": {
                    "type": "string",
                    "example": "Dune"
                },
                "rating": {
                    "type": "number",
                    "example": 7.5
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal error"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "example@mail.com"
                },
                "id": {
                    "type": "string",
                    "example": "a9aec972-2c52-441a-8f17-79506cd34366"
                },
                "name": {
                    "type": "string",
                    "example": "example_name"
                },
                "password": {
                    "type": "string",
                    "example": "example_pass"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "158.160.124.149:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Movie JSON API",
	Description:      "API Server for MovieRecommendation Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
